import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./src/components/navabar";
import Footer from "./src/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
        {/* Navbar at top */}
        <Navbar />

        {/* Main page content */}
        <main className="flex-1" style={{ paddingTop: "90px" }}>
          {children}
        </main>

        {/* Footer at bottom */}
        <Footer />
      </body>
    </html>
  );
}