import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./src/components/navabar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Navbar appears on every page automatically */}
        <Navbar />

        {/* Push page content below the navbar */}
        <main style={{ paddingTop: "90px" }}>
          {children}
        </main>
      </body>
    </html>
  );
}